name: toast-notification

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0

      - name: Install dependencies
        run: npm install

      - name: Execute linter
        run: npm lint

      - name: Build
        run: npm build

      - name: Set Registry
        run: npm set "https://registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}"

      - name: Publish to npm
        run: npm publish

        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
